### ISSUE TITLE
[BUG] Exception in getResultSet

### ISSUE THREAD

**Issue by lakhoune** [rwth-acis/mobsos-query-visualization#15]
1. **Summary** - Exception in getResultSet is thrown on some queries (which are semantically correct). 
    
```txt
i5.las2peer.api.ServiceException: Exception in getResultSet
	at i5.las2peer.services.mobsos.queryVisualization.QueryVisualizationService.getResultSet(QueryVisualizationService.java:448)
	at i5.las2peer.services.mobsos.queryVisualization.QueryVisualizationService.executeSQLQuery(QueryVisualizationService.java:402)
	at i5.las2peer.services.mobsos.queryVisualization.QueryVisualizationService.createQueryString(QueryVisualizationService.java:325)
	at i5.las2peer.services.mobsos.queryVisualization.QueryVisualizationService$Resource.createQuery(QueryVisualizationService.java:2028)
	at i5.las2peer.services.mobsos.queryVisualization.QueryVisualizationService$Resource.visualizeQuery(QueryVisualizationService.java:1922)
	at jdk.internal.reflect.GeneratedMethodAccessor22.invoke(Unknown Source)
```
   2. **When?/How often?** -It only occurs on some queries
   4. **How?/Current state** - when posting the following query: `SELECT TIME_STAMP, count(*) as 'number of requests' FROM MESSAGE WHERE JSON_EXTRACT(REMARKS,"$.botname") like "%mensa%" GROUP BY Date(TIME_STAMP)` the exception occurs

**Comment by lakhoune** [comment]
%mensa% is not correct
